import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

/**
 * Replaces the HestiaCP-autogenerated robots.txt currently served by
 * garagepass.co, which carried `Crawl-delay: 10` (Bing honours this and
 * throttles to roughly one page every ten seconds) and declared no sitemap
 * at all. Both are fixed here.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        // Nothing user-facing lives under these; keep them out of the index.
        disallow: ["/api/", "/_next/"],
      },
    ],
    sitemap: `${site.url}/sitemap.xml`,
    host: site.url,
  };
}
